# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-20 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_auto_20180420_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followed_users',
            field=models.ManyToManyField(related_name='_user_followed_users_+', to='fitness_app.User'),
        ),
    ]
